name: Build

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'
                java-package: 'jdk+fx'

            - name: Setup Maven
              env:
                TOKEN: ${{ secrets.GITHUBTOKEN }}
                USERNAME: JeffreyRiggle
              run: |
                envsubst < settings.tmpl > ~/.m2/settings.xml

            - name: Build panels
              working-directory: installpanels
              run: xvfb-run mvn install

            - name: screen resolution
              run: |
                system_profiler SPDisplaysDataType | grep Resolution
                "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
                system_profiler SPDisplaysDataType | grep Resolution
            
            - name: Build with Maven
              run: xvfb-run mvn test

            - name: Install
              run: xvfb-run mvn install

            - name: Capture Failure
              if: ${{ failure() }}
              run: |
                mkdir screencaps
                find ./ -type f | grep -i testFailure.*.png$ | xargs -i cp {} screencaps
                tar -czvf screencaps.tar.gz screencaps

            - name: Upload failure artifacts
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                name: testfx-test
                path: screencaps.tar.gz
